# Install python
FROM python:3.10-slim

# Set working directory
WORKDIR /test

# Copy project
ADD . /test

# set environment variables
ENV PYTHONPATH=/test
ENV SQLALCHEMY_DATABASE_URL="postgresql+asyncpg://postgres:postgres@db:2121/resto"
ENV URL="http://app-test:8000"

# Install dependencies
RUN pip install -r requirements.txt

# Run pytest when the container launches
CMD ["pytest tests"]
