version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_app
    restart: always
    command: -p 2121
    expose:
      - 2121
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app_ylab
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
