"""Database creation

Revision ID: 737c1af8cd66
Revises: 
Create Date: 2023-08-08 10:11:14.441164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737c1af8cd66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_Menus_id'), 'Menus', ['id'], unique=False)
    op.create_table('Submenus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_Submenus_id'), 'Submenus', ['id'], unique=False)
    op.create_table('Dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('main_menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Submenus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_Dishes_id'), 'Dishes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Dishes_id'), table_name='Dishes')
    op.drop_table('Dishes')
    op.drop_index(op.f('ix_Submenus_id'), table_name='Submenus')
    op.drop_table('Submenus')
    op.drop_index(op.f('ix_Menus_id'), table_name='Menus')
    op.drop_table('Menus')
    # ### end Alembic commands ###
